// Every user-facing string of the UI. Backend error bodies (`detail`) are already
// Turkish (SPEC_02 §13) and are shown verbatim — they are not re-translated here.
export const S = {
  app: "Balbal",
  loading: "Yükleniyor…",
  nav: { home: "Ana sayfa", ask: "Balbal'a Sor", logout: "Çıkış" },
  login: {
    title: "Giriş yap",
    subtitle: "Şirket hesabınızla giriş yapın.",
    username: "Kullanıcı adı",
    password: "Şifre",
    showPassword: "Şifreyi göster",
    hidePassword: "Şifreyi gizle",
    submit: "Giriş yap",
    submitting: "Giriş yapılıyor…",
    help: "Şifrenizi unuttuysanız veya hesabınız yoksa sistem yöneticinize başvurun.",
    slogan: "Ideas in Depth",
    pitch: "Şirketinizin belgeleri tek yerde. Balbal, yalnızca yetkiniz olan belgelerden, kaynağını göstererek cevap verir.",
    accessNote: "Erişim, departmanınıza ve yetkinize göre açılır.",
  },
  home: {
    title: "Departmanlar",
    noDepartments: "Erişebildiğiniz bir departman yok.",
    askTitle: "Balbal'a Sor",
    askHint: "Yetkinizin izin verdiği tüm belgelerde arar.",
    askButton: "Soru sor",
    agendaTitle: "Gündeminiz",
    agendaEmpty: "Şu an takip etmeniz gereken bir uyarı yok.",
    agendaPending:
      "Onay bekleyen işler, süresi dolacak belgeler ve görüş talepleri burada özetlenecek.",
    due: "Son tarih",
  },
  department: {
    tabs: { ask: "Balbal'a Sor", documents: "Belgeler", upload: "Belge Yükle", projects: "Projeler" },
    subAll: "Tümü",
    subNote:
      "Alt departman seçimi yalnızca belge listesini filtreler; sorular departmanın tamamında arar.",
    notFound: "Departman bulunamadı.",
  },
  ask: {
    generalTitle: "Genel Sor",
    scopeNote: (name: string) => `Yalnızca ${name} belgelerinde arar.`,
    placeholder: "Sorunuzu yazın",
    submit: "Sor",
    submitting: "Cevap bekleniyor…",
    examples: "Örnek:",
    exampleQuestions: [
      "Ankara RES'in güncel minimum DSCR covenant'ı nedir?",
      "Ankara RES 2026 Q2 DSCR kaç?",
      "Güncel DSCR kaç?",
      "İzmir RES'in COD tarihi nedir?",
    ],
    /** Excel hesabı isteyen örnekler — yalnızca Ürün 2 açıkken gösterilir (ADR-022). */
    exampleQuestionsP2: ["Ankara RES 2026 Q2 DSCR kaç?", "Güncel DSCR kaç?"],
    productLevelTitle: "Cevabı veren ürün katmanı",
    /** Ç-7 veri durumu etiketleri (Balbal Anayasası v2.0). */
    warningKind: {
      missing_data: "Veri yok",
      insufficient_data: "Yeterli veri bulunmamaktadır",
      product_limit: "Paket sınırı",
    },
    answerTitle: "Cevap",
    sourcesTitle: "Kaynaklar",
    excelSourcesTitle: "Excel kaynakları",
    noSources: "Kaynak gösterilmedi.",
    queryType: {
      DOCUMENT_QUERY: "Belge",
      DATA_QUERY: "Excel",
      MIXED_QUERY: "Belge + Excel",
      GENERAL_QUERY: "Genel bilgi",
    },
    sheet: "Sayfa (sheet)",
    range: "Aralık",
    downloadWorkbook: "Dosyayı indir",
    current: "GÜNCEL",
    historical: "TARİHSEL",
    page: "Sayfa",
    version: "Versiyon",
    date: "Tarih",
    effective: "Yürürlük",
    supersedes: (title: string) => `"${title}" belgesini değiştirir`,
    supersededBy: (title: string) => `"${title}" tarafından değiştirildi`,
    project: "Proje",
    model: "Model",
    tokens: "token",
    download: "Belgeyi indir",
  },
  balbal: {
    open: "Balbal'ı aç",
    newQuestion: "Yeni soru",
    history: "Geçmiş sorular",
    noHistory: "Henüz soru sormadınız.",
    privacy:
      "Sorularınız 90 gün denetim kaydında tutulur ve yalnızca sistem yöneticisi görebilir. Başka kullanıcıların cevaplarını etkilemez.",
    sessionOnly:
      "Geçmiş şimdilik yalnızca bu oturumda tutuluyor. Sorularınız 90 gün denetim kaydında saklanır, yalnızca sistem yöneticisi görür.",
    scope: "Kapsam",
    project: "Proje",
    allProjects: "Tüm projeler",
    allDepartments: "yetkili tüm departmanlar",
    emptyTitle: "Size nasıl yardımcı olabilirim?",
    emptyHint:
      "Yalnızca yetkili olduğunuz şirket belgelerinden cevap veririm ve her cevapta kaynağını gösteririm. Kaynak bulamazsam bunu açıkça söylerim.",
    placeholder: "Balbal'a bir şey sorun…",
    thinking: "Balbal yetkili belgelerinizi tarıyor…",
    footnote: "Balbal belgelerde yazanı aktarır; yorum veya tahmin eklemez.",
    footnoteP2: "Balbal belgelerde yazanı aktarır; yorum veya tahmin eklemez. Hesaplamalar Excel verisinden sistem tarafından yapılır.",
    noSourcePrefix: "İlgili belge sistemde yoksa",
    uploadLink: "belge yükleyebilirsiniz",
    noSourceSuffix: "; yüklendikten sonra Balbal bu soruyu cevaplayabilir.",
    useful: "Yararlı",
    report: "Hatalı bildir",
    feedbackThanks: "Teşekkürler.",
    feedbackReported: "Bildiriminiz sistem yöneticisine iletildi.",
    feedbackPending: "Geri bildirim kaydı için backend bekleniyor.",
  },
  team: {
    title: "Sohbetler",
    open: "Ekip sohbetini aç",
    newChat: "Yeni sohbet",
    search: "Kişi veya sohbet ara",
    filterAll: "Tümü",
    filterUnread: "Okunmamış",
    filterRequests: "Görüş talepleri",
    pendingChats: "Kişiler arası sohbet için sunucu desteği gerekiyor.",
    pendingDirectory: "Şirket rehberi için sunucu desteği gerekiyor (şu an kullanıcı listesi yalnızca yöneticiye açık).",
    requestTag: "Görüş talebi",
    directory: "Şirket rehberi",
    emptyHint: "Bir sohbet seçin veya yeni sohbet başlatın.",
    tabPeople: "Kişi / Grup",
    tabRequest: "Departmandan görüş talebi",
    directorySearch: "İsim, unvan veya departman ara",
    allDepartments: "Tümü",
    selected: "Seçilenler",
    start: "Sohbeti başlat",
    startGroup: (n: number) => `Grup sohbeti başlat (${n} kişi)`,
    requestHint:
      "Başka bir departmandan resmi görüş isteyin. Talep ilgili departmanın gündemine düşer; talep ve cevap kurumsal hafızaya kaydedilir.",
    requestTo: "Hangi departmandan?",
    requestSubject: "Konu",
    requestBody: "Talebiniz",
    requestDue: "Cevap için son tarih",
    requestSend: "Talebi gönder",
    requestStatus: { open: "Cevap bekliyor", answered: "Cevaplandı", closed: "Kapandı" },
    members: "kişi",
    shareFromSystem: "Sistemdeki belgelerden paylaş",
    shareHint: "Yalnızca görme yetkiniz olan belgeler listelenir.",
    attach: "Belge ekle",
    placeholder: "Mesaj yazın…",
    send: "Gönder",
  },
  shell: {
    search: "Belge, proje veya kişi ara",
    searchHint: "Belge, proje veya kişi arayın",
    resultsFor: (q: string) => `“${q}” için sonuçlar`,
    askBalbal: "Balbal'a sor",
    documents: "Belgeler",
    recentDocuments: "Belgeleriniz",
    projects: "Projeler",
    people: "Kişiler",
    snippetPage: (page: number) => `s. ${page}`,
    noResults: "Yetkiniz olan kayıtlarda eşleşme yok. Belge içeriğinde aramak için Balbal'a sorun.",
    searchFoot: "Yalnızca görme yetkiniz olan belgeler, projeler ve kişiler listelenir.",
    upload: "Belge yükle",
    notifications: "Bildirimler",
    notificationsPending: "Onay bekleyen işler, görüş talepleri ve belge bildirimleri burada görünecek.",
    markAllRead: "Tümünü okundu say",
    all: "Tümü",
    awaitingApproval: "Onayımı bekleyen",
    openChat: "Sohbeti aç",
    userMenu: "Kullanıcı menüsü",
    myAccess: "Yetkilerim",
    accessEmployee: (depts: string) => `${depts} departmanının normal gizlilikteki belgeleri. Diğer departmanlar için görüş veya evrak talebi.`,
    accessManager: (depts: string) => `${depts} departmanının normal ve kısıtlı gizlilikteki belgeleri (yönetim kurulu belgeleri hariç).`,
    accessManagement: "Tüm departmanların tüm gizlilik düzeyindeki belgeleri.",
    accessAdmin: "Sistemdeki tüm belgeler ve yönetim ekranları.",
    kvkkTitle: "Kişisel verileriniz (KVKK)",
    kvkkBody:
      "Balbal'a sorduğunuz sorular 90 gün denetim kaydında tutulur ve yalnızca sistem yöneticisi görebilir. Sorularınız şirket belgelerine eklenmez, başka kullanıcıların cevaplarını etkilemez.",
    myDocuments: "Belgelerim",
    sessionNote: "Oturum 8 saat sonra kendiliğinden kapanır.",
  },
  workbook: {
    title: "Excel dosya yapısı",
    sheets: "Sayfalar",
    hidden: "gizli",
    namedRanges: "Adlandırılmış aralıklar",
    tables: "Tablolar",
    formulas: "Formül hücresi",
    macros: "Makro",
    macrosYes: "Var (çalıştırılmaz)",
    no: "Yok",
    recalc: "Yeniden hesaplama",
    recalcNeeded: (n: number) => `Gerekli — ${n} formülün kayıtlı sonucu yok`,
    note: "Hesaplamaları yapay zekâ değil sistem yapar; Balbal yalnızca sonucu ve kaynağını aktarır.",
  },
  documents: {
    title: "Belgeler",
    folders: {
      own: "Departmanımın klasörleri",
      shared: "Bana açılan klasörler",
      note: "Yalnızca erişiminiz olan klasörler görünür. Klasör yetkilerini sistem yöneticisi belirler.",
      read: "Görme",
      write: "Değiştirme",
      root: "Kök klasör",
      ownNote: "Departmanınızın klasörü. Belge yükleyebilir ve bilgilerini düzenleyebilirsiniz.",
      sharedNote: (owner: string) => `${owner} departmanının klasörü. Belgeleri açıp indirebilirsiniz; yükleme ve düzenleme yetkiniz yok.`,
      writeNote: (owner: string) => `${owner} departmanının klasörü. Belge yükleme ve düzenleme yetkiniz var.`,
      uploadHere: "Bu klasöre yükle",
      search: "Bu klasörde ara",
      project: "Proje",
      allProjects: "Tümü",
      empty: "Bu klasörde eşleşen belge yok. İçerikte aramak için Balbal'a sorabilirsiniz.",
    },
    empty: "Bu kapsamda belge yok.",
    columns: {
      title: "Başlık",
      type: "Tür",
      counterparty: "Muhatap",
      date: "Tarih",
      status: "Durum",
      confidentiality: "Gizlilik",
      ingestion: "İşlem",
      project: "Proje",
      subdepartment: "Alt departman",
      kind: "Dosya",
    },
    download: "İndir",
    open: "Belgeyi aç",
    openVersion: "Belgeyi aç",
    detail: "Belge detayı",
    close: "Kapat",
    tags: "Etiketler",
    effectiveDate: "Yürürlük tarihi",
    expirationDate: "Bitiş tarihi",
    version: "Versiyon",
    supersedes: "Değiştirdiği belge",
    supersededBy: "Yerini alan belge",
    pages: "Sayfa sayısı",
    ingestionError: "İşlem hatası",
    none: "—",
  },
  upload: {
    title: "Belge Yükle",
    folder: "Klasör",
    folderHint: "Yalnızca belge yükleme (değiştirme) yetkiniz olan klasörler listelenir. Belgenin departmanı klasörden gelir; kimin görebileceğini klasör yetkileri belirler.",
    noWritableFolder: "Belge yükleyebileceğiniz bir klasör yok. Sistem yöneticinize başvurun.",
    file: "Dosya (PDF, PNG, JPG, Excel, CSV — en fazla 50 MB)",
    titleField: "Başlık",
    type: "Belge türü",
    counterparty: "Muhatap",
    date: "Belge tarihi",
    status: "Durum",
    confidentiality: "Gizlilik",
    project: "Proje",
    projectNone: "Proje yok",
    subdepartment: "Alt departman",
    subNone: "Belirtilmedi",
    effectiveDate: "Yürürlük tarihi (opsiyonel)",
    version: "Versiyon",
    supersedes: "Şu belgeyi değiştirir (opsiyonel)",
    supersedesNone: "Yok",
    submit: "Yükle",
    submitting: "Yükleniyor…",
    processing: "Belge işleniyor (OCR ve metin çıkarma)…",
    ready: "Belge hazır.",
    failed: "Belge işlenirken hata oluştu:",
    another: "Yeni belge yükle",
  },
  suggestion: {
    title: "AI metadata önerisi",
    waiting: "Öneri hazırlanıyor… (arka planda, genellikle 15 saniye içinde)",
    notYet: "Bu belge için henüz öneri yok.",
    generate: "Şimdi üret",
    retry: "Tekrar dene",
    failed: "Öneri üretilemedi:",
    apply: "Seçilenleri uygula",
    reject: "Reddet",
    adminOnly: "Bu belgenin bilgilerini yükleyen kişi onaya gönderir; yönetici düzenleyebilir.",
    applyNote: "Uygulamak belgeyi yayınlamaz; yayın, yükleyenin onaya göndermesi ve departman yetkilisinin onayıyla olur.",
    includeHint: "Yalnızca işaretlenen alanlar belgeye yazılır; diğerleri dokunulmadan kalır.",
    nothingSelected: "Uygulanacak alan seçilmedi.",
    suggested: "Önerilen",
    currentValue: "Mevcut",
    confidence: "güven",
    model: "Model",
    status: {
      pending: "Bekliyor",
      applied: "Uygulandı",
      rejected: "Reddedildi",
      failed: "Hata",
    },
  },
  /** B-28 iki aşamalı onay (Çekirdek O-1): 1. aşama yükleyen, 2. aşama departman yetkilisi. */
  review: {
    panelTitle: "Belge bilgilerini kontrol edin ve onaya gönderin",
    panelHint: "Balbal'ın önerilerini kontrol edin, gerekirse düzeltin. Belge, departman yetkilisi onayladıktan sonra aramada ve Balbal'ın cevaplarında görünür.",
    panelHintWorkbook: "Excel dosyası için öneri üretilmez; girdiğiniz bilgileri kontrol edip onaya gönderin.",
    confirm: "Onaylıyorum",
    confirmHint: "Balbal bu değerden emin değil; aynen kalacaksa onaylayın veya düzeltin.",
    submit: "Onaya gönder",
    resubmit: "Yeniden onaya gönder",
    submitting: "Gönderiliyor…",
    waitingSuggestion: "Balbal belgeyi okuyor; öneri gelince gönderebilirsiniz.",
    sentTitle: "Onaya gönderildi",
    sentText: "Departman yetkilisi onayladıktan sonra belge aramada ve Balbal'ın cevaplarında görünür.",
    publishedTitle: "Yayınlandı",
    publishedText: "Belge aramada ve Balbal'ın cevaplarında görünür.",
    statusTitle: "Onay durumu",
    submittedAt: "Onaya gönderildi",
    reviewedAt: "Karar",
    comment: "Geri gönderme açıklaması",
    approve: "Onayla",
    requestChanges: "Geri gönder",
    requestTitle: "Belgeyi geri gönder",
    requestHint: "Yükleyen kişi açıklamanızı görür, bilgileri düzeltir ve yeniden onaya gönderir.",
    requestPlaceholder: "Ne düzeltilmeli?",
    cancel: "Vazgeç",
    sending: "Gönderiliyor…",
    pendingNote: {
      pending_metadata: "Yükleyen kişi henüz bilgileri onaya göndermedi.",
      pending_review: "Departman yetkilisinin kararını bekliyor.",
      changes_requested: "Yükleyen kişiye geri gönderildi; düzeltip yeniden onaya göndermeli.",
      approved: "Onaylı.",
    },
    filterAll: "Tümü",
    eventsTitle: "Kayıt defteri",
    eventsEmpty: "Henüz kayıt yok.",
    eventCols: { time: "Zaman", who: "Kim", what: "Olay", field: "Alan", change: "Önce → Sonra", confidence: "Güven" },
    editNote: "Onaylı bir belgenin bilgisi değişirse onayı düşer ve departman yetkilisi yeniden onaylar.",
    visibilityPending: "Belge henüz yayınlanmadı: aşağıdaki liste onu şu an işleyebilen kişilerdir.",
  },
  projects: {
    title: "Projeler",
    empty: "Bu departmana bağlı proje yok.",
    columns: { name: "Ad", code: "Kod", stage: "Aşama", active: "Durum" },
    active: "Aktif",
    inactive: "Pasif",
    new: "Yeni proje",
    edit: "Düzenle",
    cancel: "Vazgeç",
    save: "Kaydet",
    saving: "Kaydediliyor…",
    name: "Proje adı",
    code: "Proje kodu (örn. ANK_RES)",
    stage: "Aşama",
    departments: "Departmanlar",
    isActive: "Aktif",
  },
  errors: {
    network: "Sunucuya ulaşılamadı.",
    generic: "Beklenmeyen bir hata oluştu.",
    requestId: "İstek no",
  },
  admin: {
    nav: "Yönetim",
    tabs: { users: "Kullanıcılar", audit: "Denetim kaydı", folders: "Klasörler ve erişim" },
    folders: {
      treeTitle: "Ortak alan klasörleri",
      newFolder: "+ Klasör",
      treeNote: "Klasör yapısı şirkete özeldir. Yetkiler bütün proje şirketlerine (SPV) aynı uygulanır.",
      shared: "paylaşılıyor",
      views: { folder: "Klasör yetkileri", matrix: "Genel tablo", history: "Değişiklik geçmişi" },
      root: "Kök klasör",
      owner: "Sahibi",
      ownerNote: "(her zaman değiştirebilir)",
      documents: "Belge",
      parent: "Üst klasör",
      department: "Departman",
      access: "Erişim",
      source: "Kaynak",
      ownerBadge: "Sahibi · değiştirebilir",
      none: "Yok",
      read: "Görme",
      write: "Değiştirme",
      srcOwner: "Klasörün departmanı",
      srcInherited: "Üst klasörden",
      srcOwn: "Bu klasörde tanımlı",
      readHelp: "listede, aramada ve Balbal'ın cevaplarında görür; açar ve indirir.",
      writeHelp: "ayrıca belge yükler, bilgilerini düzenler, yeni versiyon ekler.",
      confNote: "Klasör yetkisi gizlilik düzeyini aşmaz: kısıtlı belgeler yalnızca o düzeye yetkili kişilere açılır. Alt klasörler, ayrı yetki tanımlanmadıkça üst klasörün yetkisini alır.",
      dirty: (n: number) => `${n} değişiklik kaydedilmedi. Kaydedince hemen geçerli olur ve denetim kaydına yazılır.`,
      cancel: "Vazgeç",
      save: "Kaydet",
      saving: "Kaydediliyor…",
      saved: "Yetkiler kaydedildi ve denetim kaydına yazıldı.",
      folderCol: "Klasör",
      legend: "Sahibi: klasörün departmanı · Değiştirme / Görme: verilen yetki · italik: üst klasörden gelen · –: erişim yok",
      histCols: { time: "Zaman", who: "Değiştiren", what: "Klasör · Departman", before: "Önceki", after: "Yeni" },
      histEmpty: "Henüz yetki değişikliği yok.",
      createTitle: "Yeni klasör",
      name: "Klasör adı",
      noParent: "— Kök klasör —",
      create: "Oluştur",
      pendingTree: "Klasör ve erişim yönetimi için sunucu desteği gerekiyor (B-26).",
      pendingAudit: "Yetki değişikliği geçmişi için sunucu desteği gerekiyor.",
      pick: "Soldan bir klasör seçin.",
    },
    users: {
      title: "Kullanıcılar",
      columns: {
        username: "Kullanıcı adı",
        displayName: "Ad soyad",
        role: "Rol",
        active: "Durum",
        departments: "Departmanlar",
      },
      active: "Aktif",
      inactive: "Pasif",
      new: "Yeni kullanıcı",
      edit: "Düzenle",
      cancel: "Vazgeç",
      save: "Kaydet",
      saving: "Kaydediliyor…",
      username: "Kullanıcı adı",
      password: "Şifre",
      displayName: "Ad soyad",
      role: "Rol",
      departments: "Departmanlar",
      isActive: "Aktif",
      selfEditHint: "Kendi hesabınızın rolünü düşüremez veya devre dışı bırakamazsınız.",
    },
    auditLog: {
      title: "Denetim Kaydı",
      filters: {
        department: "Departman",
        project: "Proje",
        queryType: "Soru türü",
        from: "Başlangıç",
        to: "Bitiş",
        hasError: "Yalnızca hatalılar",
        allDepartments: "Tüm departmanlar",
        allProjects: "Tüm projeler",
        allTypes: "Tümü",
        apply: "Filtrele",
      },
      columns: {
        time: "Zaman",
        question: "Soru",
        queryType: "Tür",
        department: "Departman",
        project: "Proje",
        model: "Model",
        tokens: "Token",
        duration: "Süre (ms)",
        error: "Hata",
      },
      empty: "Kayıt yok.",
      detail: "Detay",
      close: "Kapat",
      answer: "Cevap",
      sources: "Kaynaklar",
      excelFiles: "Excel dosyaları",
      cost: "Maliyet",
      requestId: "İstek no",
      none: "—",
      prevPage: "Önceki",
      nextPage: "Sonraki",
    },
    visibility: {
      title: "Bu belgeyi kim görebilir",
      empty: "Görebilen kullanıcı yok.",
    },
    metadataEdit: {
      title: "Metadata düzenle (elle)",
      save: "Kaydet",
      saving: "Kaydediliyor…",
      hint: "Yalnızca değiştirmek istediğiniz alanları doldurun; boş bırakılanlar dokunulmadan kalır.",
    },
  },
  /** ÜRÜN 1 ARAYÜZÜ — yalnızca Ürün 1 paketinde görünen sade ana sayfa (pages/urun1/Urun1Home.tsx). */
  urun1: {
    greeting: (name: string) => (name ? `İyi günler, ${name}` : "İyi günler"),
    barLabel: "Balbal'a sorun",
    placeholder: "Balbal'a sorun: belge, sözleşme, madde, tarih…",
    placeholderFollow: "Devam edin veya yeni bir soru sorun…",
    send: "Sor",
    newQuestion: "Yeni soru",
    examples: {
      finans: [
        "Ankara RES kredi sözleşmesinin vadesi ne zaman doluyor?",
        "Kredi sözleşmesinin son tadili hangi maddeleri değiştirdi?",
        "Ankara RES sigorta poliçesi ne zaman bitiyor?",
      ],
      mali_isler: [
        "Son yüklenen fatura hangi iş için kesildi?",
        "2025 bağımsız denetim raporunu hangi firma hazırladı?",
        "Vergi levhasının güncel hali hangisi?",
      ],
      hukuk: [
        "Ankara RES EPC sözleşmesinde gecikme cezası maddesi nedir?",
        "İzmir RES davasında son duruşma ne zaman yapıldı?",
        "Hisse rehni sözleşmesi hangi bankayla imzalandı?",
      ],
      idari_isler: [
        "Ofis kira sözleşmesi ne zaman sona eriyor?",
        "Şirket araçlarının kasko poliçeleri hangi sigortada?",
        "Jeneratör bakım sözleşmesi kiminle yapıldı?",
      ],
      ik: [
        "Personel yönetmeliğine göre fazla mesai nasıl onaylanır?",
        "Yıllık izin süreleri yönetmelikte nasıl tanımlı?",
        "Organizasyon şemasının güncel hali hangisi?",
      ],
      enerji_grubu: [
        "İzmir RES ÇED başvurusu hangi tarihte yapıldı?",
        "Ankara RES son arıza raporu neyi anlatıyor?",
        "İzmir RES bağlantı görüşü hangi trafo merkezini gösteriyor?",
      ],
      default: [
        "Bu departmanın en son yüklenen belgesi hangisi?",
        "Güncel sözleşmelerimiz hangileri?",
        "Bu konuyla ilgili belge var mı?",
      ],
    },
  },
} as const;
